name: GitHub Terraform Workflow

on:
  pull_request: 
    branches: [main]
  push: 
    branches: [main]

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  terraform:
    uses: badbort/workflows/.github/workflows/terraform-azure.yaml@main
    with:
      environment: main
      directory: test
      tf_apply_branch: main
      mutex-branch: gh-mutex
    secrets: 
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      GH_READ_TOKEN: ${{ secrets.GH_READ_TOKEN }}
